Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pycse import regress
import numpy as np
time = np.array([0.0, 50.0, 100.0, 150.0, 200.0, 250.0, 300.0])
Ca = np.array([50.0, 38.0, 30.6, 25.6, 22.2, 19.5, 17.4])*1e-3

T = np.column_stack([time**0, time, time**2, time**3, time**4])

alpha = 0.05
p, pint, se = regress(T, Ca, alpha)
print(pint)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpycse[39;00m [38;5;28;01mimport[39;00m regress
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      3[0m time [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m0.0[39m, [38;5;241m50.0[39m, [38;5;241m100.0[39m, [38;5;241m150.0[39m, [38;5;241m200.0[39m, [38;5;241m250.0[39m, [38;5;241m300.0[39m])

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycse/__init__.py:22[0m
[1;32m      9[0m [38;5;66;03m# * Setup inline images for IPython[39;00m
[1;32m     10[0m [38;5;66;03m# Make inline figures the default[39;00m
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mPYCSE[39;00m [38;5;28;01mimport[39;00m (
[1;32m     13[0m     polyfit,
[1;32m     14[0m     regress,
[0;32m   (...)[0m
[1;32m     20[0m     lbic,
[1;32m     21[0m )
[0;32m---> 22[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m feq, flt, fgt, fle, fge, read_gsheet
[1;32m     24[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mhashcache[39;00m [38;5;28;01mimport[39;00m hashcache
[1;32m     26[0m [38;5;66;03m# from .beginner import *[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pycse/utils.py:13[0m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcontextlib[39;00m [38;5;28;01mimport[39;00m contextmanager
[1;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m---> 13[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21mfeq[39m(x, y, epsilon[38;5;241m=[39mnp[38;5;241m.[39mspacing([38;5;241m1[39m)):
[1;32m     17[0m [38;5;250m    [39m[38;5;124;03m"""Fuzzy equals.[39;00m
[1;32m     18[0m 
[1;32m     19[0m [38;5;124;03m    x == y with tolerance[39;00m
[1;32m     20[0m [38;5;124;03m    """[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pandas'

